packages:
  - "packages/*"

catalog:
  effect: 4.0.0-rc.117
  "@effect/platform-node": 4.0.0-rc.117
  "@effect/sql-pg": 4.0.0-rc.117

allowBuilds:
  cpu-features: true
  dprint: true
  msgpackr-extract: true
  protobufjs: true
  ssh2: true
